KwejkAdminBundle_admin_kwejk_admin_bundle_user:
    resource: "@KwejkAdminBundle/Controller/User/"
    type:     admingenerator
    prefix:   /admin/user

KwejkAdminBundle_admin_kwejk_admin_bundle_comment:
    resource: "@KwejkAdminBundle/Controller/Comment/"
    type:     admingenerator
    prefix:   /admin/comment

KwejkAdminBundle_admin_kwejk_admin_bundle_mem:
    resource: "@KwejkAdminBundle/Controller/Mem/"
    type:     admingenerator
    prefix:   /admin/mem

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

kwejk_mems:
    resource: "@KwejkMemsBundle/Resources/config/routing.yml"
    prefix:   /

kwejk_user:
    resource: "@KwejkUserBundle/Resources/config/routing.yml"
    prefix:   /

kwejk_admin:
    resource: "@KwejkAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
    

